#!/bin/bash

export DEBIAN_FRONTEND=noninteractive

dependencies=(
  "bash"
  "libc6"
  "procps"
  "sysstat"
  "net-tools"
  "hostname"
  "coreutils"
  "systemd"
  "lsb-release"
  "util-linux"
  "iproute2"
)

for dep in "${dependencies[@]}"; do
    if ! dpkg-query -l "$dep" &> /dev/null; then
        echo "$dep is not installed. Installing..."
        apt-get install -y "$dep"
    else
        echo "$dep is already installed."
    fi
done


chmod 755 /usr/bin/borninfo

echo " The BIF System Is Ready to Use "

exit 0
